accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name="signup")
]

tickbox/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', include("django.contrib.auth.urls")),
    path('register/', include('accounts.urls')),
    path('', include('todo.urls')),
]

todo/urls.py
from django.urls import path
from .views import Home, CreateNewTask, UpdateTask, DeleteTask, mark_done

urlpatterns = [
    path('task/new/', CreateNewTask.as_view(), name='new_task'),
    path('task/<int:pk>/edit/', UpdateTask.as_view(), name='update_task'),
    path('task/<int:pk>/delete/', DeleteTask.as_view(), name="del_task"),
    path('task/<int:pk>/mark_done', mark_done, name='mark_done'),
    path('', Home.as_view(), name='home'),
]

accounts/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models
from django.urls import reverse

class Task(models.Model):
    title = models.CharField(max_length=50)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.title[:25]
    
    def get_absolute_url(self):
        return reverse('home')


accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')
    
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['username'].help_text = ""
        self.fields['password1'].help_text = ""
        self.fields['password2'].help_text = ""

accounts/views.py
# from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import CustomUserCreationForm

class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = "registration/signup.html"

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Task


class Home(ListView):
    model = Task
    template_name = "home.html"


class CreateNewTask(CreateView):
    model = Task
    template_name = "task_new.html"
    fields = ["title", "status"]


class UpdateTask(UpdateView):
    model = Task
    template_name = "task_edit.html"
    fields = ["title", "status"]

class DeleteTask(DeleteView):
    model = Task
    template_name = "task_del.html"
    success_url = reverse_lazy('home')


def mark_done(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.status = True
    task.save()
    return redirect('home')


templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'icons/favicon.ico'%}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
    rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Task Management</title>

    <style>
         html, body {
            height: 100%;
            margin: 0;
        }
        .d-flex.flex-column.min-vh-100 {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        .flex-grow-1 {
            flex: 1;
        }
    </style>
</head>
<body>
    <div class="d-flex flex-column min-vh-100">
        <header class="d-flex justify-content-between align-items-center p-3 bg-light border-bottom" style="padding: 5px !important;">
            <div class="logo"><img src="{% static 'icons/navbar_logo.svg' %}" alt="navbar logo" width="45px" height="45px"></div>
            <a class="btn btn-primary" href="{% url 'new_task' %}">Create</a>
        </header>
        <div class="flex-grow-1">
            {% block content %}
            {%  endblock %}
        </div>
        
        <footer class="bg-light p-3 text-center border-top footer-content" style="padding: 0 !important;">
            
            <div class="d-flex justify-content-between align-items-center">
                <p><a href="#" class="btn btn-link">Back to the top</a></p>
                <div class="d-flex justify-content-center align-items-center" style="flex-grow: 1;">
                    <div class="copyright-text">© 2024 TickBox</div>
                </div>
                <div class="d-flex justify-content-center align-items-center">
                    {% if user.is_authenticated %}
                        <p>Welcome {{user.username}} </p> |
                        <a href="{% url 'logout' %}" class="btn btn-link" style="padding: 0 !important;">Logout</a>
                    {% else %}
                        <p>You're Not Logged In</p> |
                        <a href="{% url 'login' %}" class="btn btn-link" style="padding: 0 !important;">Log In</a>
                    {% endif %}
                </div>
                
            </div>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <main class="container my-4 flex-grow-1">
        <table class="table table-bordered">
            <thead style="background-color: lightgray;">
                <tr>
                    <th scope="col">Row</th>
                    <th scope="col">State</th>
                    <th scope="col">Title</th>
                    <th scope="col">Del/Edit</th>
                    <th scope="col">Done</th>
                </tr>
            </thead>
            <tbody>
                {% for tsk in task_list %}
                    <tr>
                        <th scope="row" style="width:30px;">{{ forloop.counter }}</th>
                        <td style="width:30px;">
                            {% if tsk.status %}
                                <img src="{% static 'icons/green-check.svg' %}" alt="green check" width="30px" heigh="30px">
                            {% else %}
                                <img src="{% static 'icons/gray-circle.svg' %}" alt="green check" width="30px" heigh="30px">
                            {% endif %}
                        </td>

                        <!-- For Edit -->
                        <td >
                            {% if not tsk.status %}
                                <p>{{ tsk.title }}</p>
                            {% else %}
                                <s>{{ tsk.title }}</s>
                            {% endif %}
                        </td>
                        <!-- -------- -->

                        <td style="width:120px;">
                            <a class="btn btn-danger btn-sm" href="{% url 'del_task' tsk.pk %}">Del</a>
                            <a class="btn btn-secondary btn-sm" href="{% url 'update_task' tsk.pk %}">Edit</a>
                        </td>
                        {% if not tsk.status %}
                            <td style="width:100px;">
                                <a class="btn btn-success btn-sm" href="{% url 'mark_done' pk=tsk.pk %}">Done</a>
                            </td>
                        {% else %}
                        <td class="thead-light" style="width:100px;border:none;">
                        </td>
                        {% endif %}
                    </tr>
                {% endfor %}
            
            </tbody>
        </table>
    </main>
{% endblock %}

        

templates/task_del.html
{% extends "base.html" %}

{% block content %}
<div class="margin-20">
  <h1>Delete Post</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ task.title }}"</p>
        <input type="submit" value="Confirm" class="btn-danger" >
    </form>  
</div>

{% endblock %}

templates/task_edit.html
{%  extends 'base.html' %}

{% block content %}
<div class="margin-20">
    <h1>Edit Task</h1>
    <form action="" method="post">{% csrf_token %} 
        {{ form.as_p }}
    <input type="submit" value="Update" class="btn btn-info">
    </form>
</div>

<style>
    form input[type="text"]{
        width: 25rem;
    }
</style>
{% endblock %}

templates/task_new.html
{% extends 'base.html' %}

{% block content %}
    <div class="margin-20">
        <h1>New Task</h1>
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Add" class="btn-info" style="width:80px;">
        </form>
    </div>
{% endblock %}
    